### ISSUE TITLE
想问下关于纯unocss写组件库的缺陷

### ISSUE THREAD

**Issue by zhou-tao** [cherryful/unocss-ui#2]
想到一个很常见的场景就是：

当用户想覆盖组件样式，是不是不方便。
因为需要覆盖unocss的通用类名来选中到目标元素，若同组件内使用了相同的原子类就会互相影响了。

**Comment by seemrcola** [comment]
参考element-plus中的bem类名规范，只要这个库加上对应规范就可以了。用户可以通过bem类名来精确覆盖样式。
至于你后面所说的 `若同组件内使用了相同的原子类就会互相影响了` 有没有具体场景呢

**Comment by zhou-tao** [comment]
是的，我想到的也是在dom上自命名，再到style标签内用@apply指令来应用unocss类的话可以规避这些问题。

**Comment by seemrcola** [comment]
嗯，我也是觉得unocss的优势之一就是可以规避由bem类名带来的复杂的样式写法
